# This is a basic workflow to help you get started with Actions

name: CD

# Controls when the workflow will run
on:
  push:
    tags: []

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  # Run CI workflow before
#  workflow_run:
#    workflows: ["CI"]
#    types:
#      - completed

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  get-artifactory:
    #    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: jfrog/setup-jfrog-cli@v2
        env:
          JF_ARTIFACTORY_1: ${{ secrets.ARTIFACTORY_TOKEN }}

      # Runs a single command using the runners shell
      - name: Set env for version name
        run: |
          echo "GITHASH=$(echo $GITHUB_SHA | cut -c 1-6)" >> $GITHUB_ENV
      - name: Get from Artifactory
        run: |
          jfrog rt ping
          jfrog rt dl "default-maven-local/petclinic/petclinic-$GITHASH.jar" petclinic.jar --flat=true
      - name: check jar file
        run: test -f petclinic.jar
      - name: copy file via ssh key
        uses: appleboy/scp-action@master
        with:
          host: cda.cefim-formation.org
          username: group2
          port: 22
          key: ${{ secrets.VM_AWS_CEFIM_KEY }}
          source: "petclinic.jar"
          target: "/home/group2/"
  launch:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: get-artifactory

    steps:
      - name: start service
        uses: appleboy/ssh-action@master
        with:
          host: cda.cefim-formation.org
          username: group2
          port: 22
          key: ${{ secrets.VM_AWS_CEFIM_KEY }}
          script: |
            sudo systemctl stop petclinic@group2.service
            sudo systemctl start petclinic@group2.service
