name: CI

on:
  push:
    branches: []
  pull_request:
    branches: []
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      githash:
        description: GitHub SHA
        default: "HEAD"

jobs:
  dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.githash }}
      - uses: actions/setup-java@v2.3.0
        with:
          java-version: "16"
          distribution: "adopt"
          cache: "maven"
      - name: Download maven dependencies
        run: mvn dependency:go-offline

  build:
    needs: dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.githash }}
      - uses: actions/setup-java@v2.3.0
        with:
          java-version: "16"
          distribution: "adopt"
          cache: "maven"
      - name: Build with maven
        run: mvn -Dmaven.test.skip=true -DskipTests -B package --file pom.xml
      - uses: actions/upload-artifact@v2.2.4
        with:
          name: petclinic_jarfile
          path: ./target/spring-petclinic-*.jar

  test:
    needs: dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.githash }}
      - uses: actions/setup-java@v2.3.0
        with:
          java-version: "16"
          distribution: "adopt"
          cache: "maven"
      - name: Test with maven
        run: mvn -B test --file pom.xml

  upload-artifactory:
    needs: [build, test]
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
      - uses: actions/download-artifact@v2.0.10
        with:
          name: petclinic_jarfile
      - uses: jfrog/setup-jfrog-cli@v2
        env:
          JF_ARTIFACTORY_1: ${{ secrets.ARTIFACTORY_TOKEN }}
      - name: Set env for version name
        run: |
          echo "GITHASH=$(echo $GITHUB_SHA | cut -c 1-6)" >> $GITHUB_ENV
      - name: Upload jar to artifactory
        run: |
          jfrog rt ping
          jfrog rt u "./spring-petclinic-*.jar" "default-maven-local/petclinic/petclinic-$GITHASH.jar" --flat=true
