name: GitHub Actions CD
on: workflow_dispatch
jobs:
  download_from_artifactory:
    runs-on: ubuntu-latest
    steps:
      - uses: jfrog/setup-jfrog-cli@v2
        env:
          JF_ARTIFACTORY_1: ${{ secrets.JFROG_TOKEN }}

      - run: jfrog rt dl --sort-by=created --sort-order=desc --limit=1 pet-klinik latest-release.jar
      - run: ls -la

      - name: copy file via scp
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_URL }}
          username: ${{ secrets.SERVER_LOGIN }}
          port: 22
          key: ${{ secrets.PEM }}
          source: "./latest-release.jar"
          target: "test"

      - name: restart service
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_URL }}
          username: ${{ secrets.SERVER_LOGIN }}
          key: ${{ secrets.PEM }}
          port: 22
          script: ls -la
